# Generated by Django 4.2.4 on 2023-12-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LasttName', models.CharField(max_length=100)),
                ('EscortID', models.IntegerField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('PhoneNumber', models.IntegerField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('ProfilePicture', models.ImageField(upload_to='photos%y%m%d')),
                ('Gender', models.BooleanField(default=True)),
            ],
        ),
    ]
