# Generated by Django 4.2.4 on 2023-12-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LasttName', models.CharField(max_length=100)),
                ('patientID', models.IntegerField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('PhoneNumber', models.IntegerField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('ProfilePicture', models.ImageField(upload_to='photos%y%m%d')),
                ('Male', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['UserName'],
            },
        ),
        migrations.AlterModelOptions(
            name='escort',
            options={'ordering': ['UserName']},
        ),
        migrations.RemoveField(
            model_name='escort',
            name='Gender',
        ),
        migrations.AddField(
            model_name='escort',
            name='Male',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='escort',
            name='feMale',
            field=models.BooleanField(default=False),
        ),
    ]
