# Generated by Django 4.2.4 on 2023-12-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0002_patient_alter_escort_options_remove_escort_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
