# Generated by Django 4.2.4 on 2023-12-12 21:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0004_diseases_medicine_rename_female_escort_female_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('ReminderID', models.IntegerField(primary_key=True, serialize=False)),
                ('patientID', models.IntegerField()),
                ('DrugName', models.CharField(max_length=50)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('State', models.BooleanField()),
                ('AlarmRecordes', models.TimeField()),
                ('Notes', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='escort',
            name='LastModified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='DiseasesID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='escort',
            name='EscortID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='escort',
            name='PhoneNumber',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='DrugID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PhoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
