# Generated by Django 4.2.4 on 2023-12-12 22:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0005_reminder_escort_lastmodified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['DrugName']},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['ReminderID']},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='EscortID',
        ),
        migrations.AddField(
            model_name='patient',
            name='deflut',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='erd.escort'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='DrugID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expire_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PhoneNumber',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='DrugName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='ReminderID',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='State',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='patientID',
            field=models.IntegerField(blank=True),
        ),
    ]
