# Generated by Django 4.2.4 on 2023-12-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0006_alter_medicine_options_alter_reminder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escort',
            name='PhoneNumber',
            field=models.CharField(max_length=14),
        ),
    ]
