# Generated by Django 4.2.4 on 2023-12-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0007_alter_escort_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escort',
            name='LastModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Duration_of_use',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='EndDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='StartDate',
            field=models.DateTimeField(),
        ),
    ]
