# Generated by Django 4.2.4 on 2023-12-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0009_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='DiseasesID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
