# Generated by Django 4.2.4 on 2023-12-12 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0010_alter_diseases_diseasesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PhoneNumber',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(14)]),
        ),
    ]
