# Generated by Django 4.2.4 on 2023-12-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0011_alter_patient_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PhoneNumber',
            field=models.CharField(max_length=100),
        ),
    ]
