# Generated by Django 4.2.4 on 2023-12-13 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0013_remove_patient_deflut'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deflut',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='erd.escort'),
        ),
    ]
