# Generated by Django 4.2.4 on 2024-02-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erd', '0014_patient_deflut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='Audio',
            field=models.FileField(default='default_audio.mp3', upload_to='audio/'),
        ),
    ]
